# Receive OTel data
[[inputs.opentelemetry]]
  service_address = "0.0.0.0:4317"

# Write to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://host.docker.internal:8086"]
  token = "dONkZBwNNLKZLl62rmhPCJFpjU8j5OnydSpwibCyAjZR3Y9y0JJV9pr2w_YH7xU6o8zwu7Ag8F6loxyBUpV3IQ"
  organization = "org"
  bucket = "bucket"